versions:
  "253.6":
    folder: all
  "252.12":
    folder: all
  "251.18":
    folder: all
  "249.16":
    folder: all
  "248.12":
    folder: all
  "247.13":
    folder: all
  "246.16":
    folder: all
